### ISSUE TITLE
Choose IDL to use to describe Steem binary serialization protocol

### ISSUE THREAD

**Issue by goldibex** [steemit/steem#1964]
We are currently looking at using an IDL to write a machine-readable description of the Steem binary serialization protocol.

The output of this issue should be a decision on which IDL to use.

Judgment criteria:
- normativity: can the IDL describe our protocol in its entirety?
- simplicity: does the IDL describe our protocol cleanly with as little boilerplate as possible?
- universality: does the IDL have client support for multiple different languages?

**Comment by goldibex** [comment]
cc @youkaicountry

**Comment by vogel76** [comment]
IDL is still in use: javascript usage: WebIDL which has been even standardized by W3C as definition of webbrowser APIs to JS. So looks like it's good candidate to describe APIs provided by Steemit tools (ie steemd) and generate documentation, target language bindings from these definitions.
As for python there is also omniORBpy tool, which does such things (and much more, as CORBA compliant) for python:
https://sourceforge.net/projects/omniorb/?source=navbar

I think it worth to think about using both tools/standards at least in part of definition interfaces/parts of software which shall be shared across languages and generate target language bindings from IDL.
IDL as a language actually should cover all needs: allows to specify methods, interfaces, fields, constants etc.

**Comment by goldibex** [comment]
"IDL" is a term of art. There are many, many different IDLs. You will have to specify one.

**Comment by vogel76** [comment]
I have put links to pages containing tools related to valid expansion of IDL acronym :-) The thing we are talking about is Interface Description Language.

**Comment by vogel76** [comment]
Here we have a WebIDL implementation tool which handles IDL definitions and processes JS output:
https://github.com/jsdom/webidl2js
Anyway always we can limit usage of IDL defs just to generate boilerplate definitions of data structures shared across languages.
The most benefit of using IDL will be (probably) not just exposing internal types (as their data-structure), which number and complexity is quite limited (but i.e. asset is complex and good candidate for exposing also methods operating on them), but in another stage APIs which definitions are complex, hard to document and correctly share across languages.

**Comment by theoreticalbts** [comment]
So I did some research on WebIDL.  There is not a lot of easily accessible "how to get started" information about WebIDL out there.  Oh, sure, the spec tells you how to write WebIDL files, but it doesn't really explain what you do with the WebIDL file once it's written.  Most of the stuff out there on "how to go from WebIDL to generated code" seems to be from the standpoint of "I want to add a feature to a web browser."  Or more generally "I have some C++ project that I want to be scriptable with JavaScript, and I want to autogenerate the glue that allows certain parts of the C++ code to be called from JavaScript."  Which is not what we want to do.

The [webidl2js utility](https://github.com/jsdom/webidl2js) mentioned in the previous comment is fine if you're writing a JS implementation of an interface specified in WebIDL.  Which is not what we want to do either.

Our goal right now is to autogenerate serialization code (and perhaps JSONRPC API bindings) [1].

The most helpful document I found is [here](https://chromium.googlesource.com/chromium/src/+/lkcr/third_party/WebKit/Source/bindings/IDLCompiler.md) in Chromium documentation.  Its input is type metadata in the form of WebIDL, and its output is a mixture of Python code and Jinja templates.  It freely admits that "The boundary between the stages of the pipeline can move, primarily in the [code generator] between the context and the template (depending on logic complexity: can it fit in the template, or should it be a Python function?)."

As far as I can tell from this, the original question posed in the opening paragraph -- "OK, I wrote a WebIDL file, what do I actually do with it?" is "After you've put your type metadata in WebIDL, you write your own WebIDL compiler, including lex + yacc + IR + backend, to generate the code you want to generate."

So the most we get from IDL is a standard language for expressing type metadata; for the most part we still need to build bespoke code for the rest of the tooling we need.  The interoperability benefits of using WebIDL are limited because the tooling is limited, and there's real technical risk that something in the WebIDL specification isn't quite compatible.

To summarize the situation so far:  Step 1 is "Put your type metadata in WebIDL," Step 2 is "write a WebIDL parser and code generation ourselves."

Now back to what would be Step 1:  "Put your type metadata in WebIDL."  This step assumes our type metadata fits well into WebIDL's type ontology.  When you're using WebIDL in JavaScript-land [2] this is a safe assumption.  But we're not in JavaScript-land.  Here's the list of potential type-ontological issues I was able to come up with after a quick read-through of the spec:

- The spec says 64-bit integers are converted to/from `double` when talking to JS, losing precision for values of magnitude greater than `2^52`.  We probably have some `uint64` values that really need all 64 bits.
- Serialization specified in WebIDL is JSON serialization only, no provision for binary serialization.  The whole point of this exercise is binary serialization so JS / Python can do its own signing.
- JSON serialization mandated by WebIDL spec may not be the same as currently provided by `steemd`, leading to compatibility issues.
- Confusing binary types:  The WebIDL spec's [advice](https://www.w3.org/TR/WebIDL/#idl-ByteString) about whether to represent binary data as `ByteString`, `DOMString`, `Sequence` or `TypedArray` is more confusing than enlightening.
- WebIDL union types may not be compatible with the `fc` union type, `fc::static_variant`.

So Step 1 is "shoe-horn C++ like data structures into a JS like data structure metadata description language," Step 2a is "write your own lex and yacc", and Step 2b is "write a code generation backend yourself."

After looking at the state of WebIDL implementations, I propose sticking with my original plan, which could be described succinctly as "create a bespoke JSON IDL to describe our type metadata."  This cuts out the C++/JS impedance mismatches in Step 1, trivializes Step 2a (every modern language has a JSON parser these days), and doesn't affect the amount of work needed for Step 2b either way.

[1] I did a search for `webidl jsonrpc` and the results were [not encouraging](https://stackoverflow.com/questions/10777910/idl-for-json-rest-rpc-interface).

[2] You're squarely in JavaScript-land if you use WebIDL for its intended use case, formalizing a web browser's DOM.  Obviously the DOM has been targeted to JS since Day One.  We don't have this, the way `steemd` objects and API's have been written is primarily targeted to C++, and JS compatibility is an afterthought by comparison.

**Comment by goldibex** [comment]
I agree with @theoreticalbts concerning WebIDL. WebIDL is not a protocol description language. It was created for the purpose of formalizing the specification of interfaces for Web browsers. The awkwardness of using such a tool in a manner other than it was intended, together with the lack of effective tooling for client autogeneration (a key target for us), makes it unsuited to our use case.

IDLs I would like us to consider include:
- [Protocol buffers](https://developers.google.com/protocol-buffers/) 
- [ASN.1](https://www.itu.int/en/ITU-T/asn1/Pages/introduction.aspx)
- [ABNF](https://en.wikipedia.org/wiki/Augmented_Backus%E2%80%93Naur_form)

I think that any one of these could provide a complete description of the serialization format. I am presently investigating protobufs.

**Comment by goldibex** [comment]
Protobuf is probably out as it has no provision for naive 16-bit values.

**Comment by goldibex** [comment]
As far as a custom format goes, @theoreticalbts, I imagine you were thinking of something like the following (in JSON-compatible strict YAML):

```
asset:
    description: >
      A fractional value of a particular unit of currency.
      Please see Steem Reference Manual §1.1 for parsing semantics.
    type: fixed_string
    length: 16
public_key:
    description: >
      A base58check-encoded secp256k1 public key.
      Please see Steem Reference Manual §1.2 for parsing semantics.
    type: string
authority:
    description: A description of which signatures are required to authorize an operation.
    type: struct
    fields:
      - name: weight_threshold
        type: uint32
      - name: account_auths
        type: map
        key_type: string
        value_type: uint16
      - name: key_auths
        type: map
        key_type: public_key
        value_type: uint16
operation:
    description: >
      A change to the state of the Steem blockchain.
      Grouped in atomic units with other operations in a transaction.
    type: static_variant
    choices:
        - account_create_operation
        - transfer_operation
account_create_operation:
    description: An operation that creates a new account on the blockchain.
    type: struct
    fields:
        - name: fee
          type: asset
        - name: creator
          type: string
        - name: name
          type: string
        - name: owner_authority
          type: authority
        - name: active_authoriy
          type: authority
        - name: posting_authority
          type: authority
        - name: memo_key
          type: public_key
        - name: json_metadata
          type: string
transfer_operation:
    description: An operation that transfers assets on the blockchain.
    type: struct
    fields:
        - name: from
          type: string
        - name: to
          type: string
        - name: amount
          type: asset
        - name: memo
          type: string

```
